apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: app
spec:
  replicas: 2
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  template:
    metadata:
      labels:
        app: app
    spec:
      containers:
      - name: app
        image: mgtns/kubernetes-repo:app 
        ports:
        - containerPort: 80
        readinessProbe:
          httpGet:
            path: /
            port: 80
